---
kind: pipeline
type: docker
name: test


steps:
- name: clone test repo
  image: node
  commands:
 - git clone https://github.com/xored2410/playwright-drone.git
 - npm install
 - npm run test:dev


# - name: playwright tests
#   image: node
#   commands:
#     - npm install
#     - npm run test:dev