---
kind: pipeline
type: docker
name: test

workspace:
  path: ./

steps:
- name: clone and run tests
  image: node
  commands:
  - git clone https://github.com/xored2410/playwright-drone.git
  - echo Trying to instal dependencies
  - cd
  - npm install
  - npm run test:dev


# - name: playwright tests
#   image: node
#   commands:
#     - npm install
#     - npm run test:dev