---
kind: pipeline
type: docker
name: console

steps:
- name: hello from pipeline
  image: busybox
  commands:
  - echo truc truc
 
trigger:
  branch:
  - main
---
  kind: pipeline
  type: docker
  name: test

steps:
- name: playwright tests
  image: node
  commands:
  - git clone https://github.com/xored2410/playwright-drone.git
  - git checkout $DRONE_COMMIT
  - npm install
  - npm run test:dev