---
kind: pipeline
type: docker
name: console

steps:
- name: hello from pipeline
  image: busybox
  commands:
  - echo truc truc
 
trigger:
  branch:
  - main
---
  kind: pipeline
  type: docker
  name: test

  trigger:
    repo:
    - playwright-drone

steps:
- name: playwright tests
  image: node
  commands:
  - npm install
  - npm run test:dev