---
kind: pipeline
type: docker
name: default

steps:
- name: hello from pipeline
  image: busybox
  commands:
  - echo truc truc
 
trigger:
  branch:
  - main
---
  kind: pipeline
  type: docker
  name: playwright tests

  trigger:
    repo:
    - xored2410/plawright-drone

steps:
- name: playwright tests
  image: node
  commands:
  - npm install
  - npm run test:dev